-- CREATE A TEMPORARY TABLE THAT WILL CONTAIN DATA IMPORTED FROM LEGACY SYSTEM WHICH IS AN EXCEL FILE IN THIS CASE.
CREATE TABLE EMP_TEMP
(
	LAST_NAME VARCHAR2(100),
	SALARY NUMBER,
	EMAIL VARCHAR2(100),
	JOB_ID VARCHAR2(100),
	DEPARTMENT_NAME VARCHAR2(100)
);