-- THE EMP_TEMP BODY
CREATE OR REPLACE PACKAGE BODY EMP_TEMP_PKG
IS 
	PROCEDURE EMP_TEMP_PRC
IS
    V_DEPT_ID NUMBER(4);
    CURSOR EMP_TEMP_CURSOR IS 
        SELECT * 
        FROM EMP_TEMP;

BEGIN 
    FOR EMP_TEMP_REC IN EMP_TEMP_CURSOR LOOP

        IF EXSISTANT_DEPT_NAME(EMP_TEMP_REC.DEPARTMENT_NAME)

            THEN            
            SELECT DEPARTMENT_ID
            INTO V_DEPT_ID
            FROM DEPARTMENTS
            WHERE DEPARTMENT_NAME = EMP_TEMP_REC.DEPARTMENT_NAME;

            INSERT INTO EMPLOYEES 
            (EMPLOYEE_ID, LAST_NAME, SALARY, EMAIL, JOB_ID, DEPARTMENT_ID)
            VALUES
            (EMPLOYEES_SEQ.NEXTVAL, EMP_TEMP_REC.LAST_NAME, EMP_TEMP_REC.SALARY, EMP_TEMP_REC.EMAIL, EMP_TEMP_REC.JOB_ID, V_DEPT_ID);
              
        ELSE

            INSERT INTO DEPARTMENTS
            (DEPARTMENT_ID ,DEPARTMENT_NAME)
            VALUES
            (DEPARTMENTS_SEQ.NEXTVAL, EMP_TEMP_REC.DEPARTMENT_NAME);


            INSERT INTO EMPLOYEES 
            (EMPLOYEE_ID, LAST_NAME, SALARY, EMAIL, JOB_ID, DEPARTMENT_ID)
            VALUES
            (EMPLOYEES_SEQ.NEXTVAL, EMP_TEMP_REC.LAST_NAME, EMP_TEMP_REC.SALARY, EMP_TEMP_REC.EMAIL, EMP_TEMP_REC.JOB_ID, DEPARTMENTS_SEQ.CURRVAL);

        END IF;
    END LOOP;
DELETE FROM EMP_TEMP;
END;

	FUNCTION EXSISTANT_DEPT_NAME(V_DEPT_NAME VARCHAR2)
RETURN BOOLEAN
IS 
    EXISTENCE BOOLEAN;
    CURSOR DEPT_CURSOR IS
        SELECT DEPARTMENT_NAME 
        FROM DEPARTMENTS
        WHERE DEPARTMENT_NAME = V_DEPT_NAME;
BEGIN
    FOR DEPT_REC IN DEPT_CURSOR LOOP
        IF DEPT_CURSOR%FOUND
        THEN 
            EXISTENCE := TRUE;
        ELSE
            EXISTENCE := FALSE;
        END IF;
    END LOOP;
    RETURN EXISTENCE;
END;
END;

