-- THIS PROCEDURE WILL MOVE THE EMP_TEMP DATA TO THEIR TABLES WHICH ARE DEPARTMENTS AND EMPLOYEES IN OUR CASE.

-- A CURSOR TO SELECT FROM ALL ROWS IN EMP_TEMP.
CREATE OR REPLACE PROCEDURE EMP_TEMP_PRC
IS
    V_DEPT_ID NUMBER(4);
    CURSOR EMP_TEMP_CURSOR IS 
        SELECT * 
        FROM EMP_TEMP;

BEGIN 
    FOR EMP_TEMP_REC IN EMP_TEMP_CURSOR LOOP

        IF EXSISTANT_DEPT_NAME(EMP_TEMP_REC.DEPARTMENT_NAME)
            THEN  
				-- IF THE DEPARTMENT NAME EXISTS IT WILL SELECT THE CORRISPONDING DEPARTMENT ID TO IT.
            SELECT DEPARTMENT_ID
            INTO V_DEPT_ID
            FROM DEPARTMENTS
            WHERE DEPARTMENT_NAME = EMP_TEMP_REC.DEPARTMENT_NAME;
				-- ALL DATA WILL BE INSERTED INTO EMPLOYEES TABLE.
				-- EMPLOYEE ID WILL BE PROVIDED AUTOMATICLY THROUGH A SEQUENCE.
            INSERT INTO EMPLOYEES 
            (EMPLOYEE_ID, LAST_NAME, SALARY, EMAIL, JOB_ID, DEPARTMENT_ID)
            VALUES
            (EMPLOYEES_SEQ.NEXTVAL, EMP_TEMP_REC.LAST_NAME, EMP_TEMP_REC.SALARY, EMP_TEMP_REC.EMAIL, EMP_TEMP_REC.JOB_ID, V_DEPT_ID);
              
        ELSE
				-- IF THE DEPARTMENT NAME DOES NOT EXIST IT WILL INSERT IT INTO DEPARTMENTS TABLE AND SELECT THE CORRISPONDING DEPARTMENT ID.
				-- DEPARTMENT ID WILL BE PROVIDED AUTOMATICLY THROUGH A SEQUENCE.
            INSERT INTO DEPARTMENTS
            (DEPARTMENT_ID ,DEPARTMENT_NAME)
            VALUES
            (DEPARTMENTS_SEQ.NEXTVAL, EMP_TEMP_REC.DEPARTMENT_NAME);
				
				-- ALL DATA WILL BE INSERTED TO EMPLOYEES TABLE.
            INSERT INTO EMPLOYEES 
            (EMPLOYEE_ID, LAST_NAME, SALARY, EMAIL, JOB_ID, DEPARTMENT_ID)
            VALUES
            (EMPLOYEES_SEQ.NEXTVAL, EMP_TEMP_REC.LAST_NAME, EMP_TEMP_REC.SALARY, EMP_TEMP_REC.EMAIL, EMP_TEMP_REC.JOB_ID, DEPARTMENTS_SEQ.CURRVAL);

        END IF;
    END LOOP;
	-- MAKE THE EMP_TEMP TABLE EMPTY AFTER A COMPLETE DATA MIGRATION.
	DELETE FROM EMP_TEMP;
END;