-- ANY FUTURE INSERTION IN THE EMP_TEMP TABLE WILL BE HANDLED AUTOMATICLY THROUGH A TRIGGER.
CREATE OR REPLACE TRIGGER EMP_TEMP_TRG
AFTER INSERT ON EMP_TEMP
DECLARE 
	EMP_TEMP_PKG.EMP_TEMP_PRC;
END;
